In [49]:
import numpy as np
from sklearn.linear_model import LinearRegression
from matplotlib import

x = np.array([[1, 4], [1, 4.5], [1, 5], [1, 5.5], [1, 6], [1, 6.5], [1, 7]])
y = np.array([33, 42, 45, 51, 53, 61, 62])

In [50]:
xTx = np.dot(x.T, x)
xTx

array([[  7.  ,  38.5 ],
       [ 38.5 , 218.75]])

In [51]:
xTx_1 = np.linalg.inv(xTx)
xTx_1

array([[ 4.46428571, -0.78571429],
       [-0.78571429,  0.14285714]])

In [52]:
xTy = np.dot(x.T, y)
xTy

array([ 347., 1975.])

In [53]:
w = np.dot(xTx_1, xTy)
w

array([-2.67857143,  9.5       ])

In [57]:
model = LinearRegression().fit(x, y)
print(model.intercept_, model.coef_)

-2.6785714285714235 [0.  9.5]
